### ISSUE TITLE
A few errors...

### ISSUE THREAD

**Issue by Darloup** [alg5/quicklanguage#27] opened 2016-04-14 00:34 UTC
Hello,

1) The instructions say: 

> Copy the entire contents from the unzipped folder to /ext/alg/quicklanguage/

Yet the downloadable file is: quicklanguage-master

You thus have to rename "quicklanguage-master" into "quicklanguage" for this extension to be recognised by phpBB as an extension...

2) I eventually manage to activate this extension, but one of my languages is missing. I have three languages on my forum: French, British English and Spanish (informal).

 I do get the French and British icon flags in the header, but NOT the Spanish flag - why?

Regards,

Hello

**Comment by alg5** [comment] 2016-04-16 07:36
> Yet the downloadable file is: quicklanguage-master

This is not an error. This name has been set by github automatically. I'd recommend  to you install the extension https://www.phpbb.com/community/viewtopic.php?f=536&t=2354991 in order to load all the other extensions

> I do get the French and British icon flags in the header, but NOT the Spanish flag - why?
> Unfortunately currently there is no support for the Spanish language.
> You could assist us in this by helping us by translating it and sending the translations to me. We would really appreciate it.

**Comment by Darloup** [comment] 2016-04-18 02:27
Hello,

This page https://github.com/BoardTools/upload/wiki/Translations shows that the Spanish version is available. Why do you need one from me?

Furthermore, I'm only interested in the facility to switch between installed languages. Do I need to upload a Spanish flag so that it works?

**Comment by alg5** [comment] 2016-04-22 14:24
You may add an icon of a Spanish flag yourself.
I'll upload Spanish support only.
The problem is there is no Spanish translation yet.
There are two alternatives ways for you.
1. You may assist us in adding Spanish translation.
2. You may wait until the translation is done by someone else.

I am closing this issue, there are no errors. You may participate in the discussion for this extension in the following link: https://www.phpbb.com/community/viewtopic.php?f=456&t=2304831

**Closed as completed by alg5** 2016-04-22 14:24 UTC
